### ISSUE TITLE
Can't dump schemas on spatial indexes

### ISSUE THREAD

**Issue by simoncozens** [rgeo/rgeo-activerecord#23]
When you call `indexes` on a connection with a spatial adapter, you get a `SpatialIndexDefinition` back, like this:

```
=> #<struct RGeo::ActiveRecord::SpatialIndexDefinition
 table="saved_searches",
 name="index_saved_searches_on_user_id",
 unique=false,
 columns=["user_id"],
 lengths=[nil],
 orders=false,
 where=nil,
 spatial=nil>
```

as defined in `common_adapter_elements.rb`: 

``` ruby
    class SpatialIndexDefinition < Struct.new(:table, :name, :unique, :columns, :lengths, :orders, :where, :spatial)
    end
```

Unfortunately as of [this patch](https://github.com/rails/rails/commit/a89e9f70b24fe9c6b4f7b9343f4dc143928f2bdb) `ActiveRecord::SchemaDumper` expects to also call the `using` method on an index object. (And similarly for [the `type` method](https://github.com/rails/rails/commit/9600e0b02973ce5dd36642511d542a6b62983a5e).)

Because there aren't `using` or `type` methods in this struct, `rake db:schema:dump` fails horribly with the following error which I reproduce for future Googlers:

```
# Could not dump table "<whatever>" because of following NoMethodError
#   undefined method `using' for #<RGeo::ActiveRecord::SpatialIndexDefinition:0x00000008386e88>
```

Adding `:using, :type` to that definition above allows the database to be dumped properly, although I'm not sure that's a perfect solution.

**Comment by keithdoggett** [comment]
Closing since the `SpatialIndexDefinition` class has been removed.
