### ISSUE TITLE
 Arel dropped Visitors::DepthFirst -> Rails 6.1.0.alpha support broken

### ISSUE THREAD

**Issue by cschoene** [rgeo/rgeo-activerecord#54]
See topic, and: https://github.com/rails/rails/commits/master/activerecord/lib/arel/visitors.rb
Crash occurs upon `rails s` on development for rails 6.1.0.alpha (and possibly others) using activerecord-postgis-adapter-6.0.0.

Since its rather clear why the name error occurs, I only included parts of the stack trace to help others track down this error.

rgeo-activerecord-6.2.1/lib/rgeo/active_record/arel_spatial_queries.rb:89:in `<module:ActiveRecord>'
...
gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant Arel::Visitors::DepthFirst (NameError)

**Comment by oyeanuj** [comment]
@teeparham Any thoughts on the fix for this (as this is on the latest Rails version)?

**Comment by oyeanuj** [comment]
@cschoene Have you found a workaround for this in the meantime?

**Comment by cschoene** [comment]
Yes & No (using the postgresql adapter for now, since I can make do without GIS-features for the time being).

**Comment by kamipo** [comment]
I've create a PR to address the issue #55.
