### ISSUE TITLE
Spatial adapter names don't play nice with existing gems

### ISSUE THREAD

**Issue by michael-groble** [rgeo/rgeo-activerecord#6]
The specific adapters all create a new spatial adapter name on top of the existing database adapter.

This causes problems with gems that would otherwise work with the base adapter.

I've fixed this issue in [activerecord-import](/michael-groble/activerecord-import/commit/19acfd9e63f3c38b82faa3abca3bf27cb476e845), but now am having the problem in [foreigner](/matthuhiggins/foreigner) which has similar adapter [load logic](/matthuhiggins/foreigner/blob/master/lib/foreigner/adapter.rb)

I'm wondering if there is a way to do this differently in rgeo that doesn't break all these other gems.

**Comment by teeparham** [comment]
My guess is that whatever these other gems are doing shouldn't be based on the name of the adapters.

I'm closing this as it's 3.5 years old.
