### ISSUE TITLE
Lost rgeo_factory_for_column after reconnect

### ISSUE THREAD

**Issue by alno** [rgeo/rgeo-activerecord#7]
Hi! Thankyou for the great gems!

But if found an issue with rgeo_factory_settings which are lost after reconnecting to database

For example my irb session:

```ruby
irb(main):020:0> OsmBuilding.rgeo_factory_settings
=> #<RGeo::ActiveRecord::RGeoFactorySettings:0x7f60f4a60318 @column_factories={"osm_buildings"=>{"geometry"=>#<RGeo::Geos::Factory:0x3fb07a54d070 srid=900913 bufres=1 flags=8>}}, @factory_generators={}>

irb(main):021:0> ActiveRecord::Base.establish_connection

irb(main):022:0> OsmBuilding.rgeo_factory_settings
=> #<RGeo::ActiveRecord::RGeoFactorySettings:0x7f60f44bb700 @column_factories={}, @factory_generators={}>
```

As you can see, all factory settings are lost.

Reconnection to database is a common practive when using some ruby servers (unicorn in my case) which preload applications and then fork workers.

Are there any reasons to bind factory settings to connection pool? Why not activerecord class?

**Comment by teeparham** [comment]
Closing, as this method was removed in version 3.0.
