### ISSUE TITLE
Example setup not compatible with RGeo 3.0

### ISSUE THREAD

**Issue by hirowatari** [rgeo/rgeo-activerecord#74]
The readme says:

> Here is an example setup:
> ```
> RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
>   # By default, use the GEOS implementation for spatial columns.
>   config.default = RGeo::Geos.factory_generator
> 
>   # But use a geographic implementation for point columns.
>   config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "point")
> end
> ```

However, in RGeo 3.0 `RGeo::Geos.factory_generator` has been removed see: https://github.com/rgeo/rgeo/pull/314

I don't understand what `config.default = RGeo::Geos.factory_generator` was doing, or how to upgrade.

Could you kindly advise on if rgeo-activerecord is compatible with RGeo 3.0 and if so what should be done to remedy the above?

**Comment by keithdoggett** [comment]
Hi @hirowatari you can just use `RGeo::Geos.factory` instead of `factory_generator`. Thanks for pointing this out. I'll update it soon.

**Comment by keithdoggett** [comment]
Fixed by https://github.com/rgeo/rgeo-activerecord/pull/72. Thanks @hirowatari

**Comment by hirowatari** [comment]
Thank you kindly for the advice, prompt response and continued work on the gem.  It's much appreciated.
