### ISSUE TITLE
Let drop support for rgeo prior 3.0

### ISSUE THREAD

**Issue by seuros** [rgeo/rgeo-activerecord#75]
@keithdoggett @BuonOmo , 
I think it will be beneficial to drop support for rgeo prior 3.x, that will make maintenance easier for future versions.

We could also drop support for unsupported version of active record.

I have a branch that I can open a PR here.

**Comment by seuros** [comment]
ping

**Comment by keithdoggett** [comment]
Were there any instances during the migration you did where this was an issue? I agree that if it becomes a maintainability issue we should drop the old versions, but I think v2 still has a lot of users so I don't necessarily want to prematurely drop it.
