### ISSUE TITLE
Column has M dimension but geometry does not

### ISSUE THREAD

**Issue by sempervictus** [rgeo/rgeo-activerecord#8]
When point is defined as:
t.point :point, :srid => 4326 , :has_z => true, :has_m => true

and the factory is defined as:
RGeo::Geographic.simple_mercator_factory(:has_z_coordinate => true, :has_m_coordinate => true, :uses_lenient_assertions => true,)

points produced by the factory have 4 dimensions, but as soon as they are assigned to the AR object, they lose the M coordinate. Attempting to save the objects results in the error listed in:
ActiveRecord::StatementInvalid: PG::Error: ERROR:  Column has M dimension but geometry does not

Rather confounding given that everything :has_m_coordinate.

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue on recent version(s).
